// bank soal (32 soal)

// Tema Sampah
	// "Please recycle plastic."
	// "The objective of cleaning is not just to clean, but to feel happiness."
	// "Being green and clean is not just an aspiration buat an action."
	// "Environmental cleanliness negins with each indivial desire to be clean."
	// "Clean and green is our prerfect dream."
	// "Be clean and healty, and a happy person."
	// "do not litter."
	// "Safe the turtle by reducing use plastic."
// Tema kesehatan
	// "Remember to wash your hand."
	// "Don't forget to take your vitamins on time."
	// "Stay safe while driving."
	// "Don't forget to check your vehicle before driving."
	// "Please sleep if you're sleepy."
	// "Don't driving while you're dunk."
	// "Always to put on you seatbelt."
	// "Safety is out forst priority."
	// "Safety rules are your best tools."
	// "Begin with safety in mind."
	// "Don't play with your phone while driving."
	// "Never let accident takes your future."
// Tema kedisplinan belajar
	// "whatever you are, be a good one."
	// "be the change you wish to see in the world."
	// "don't forget to study everyday."
	// "it's time for school."
	// "Try and fail, but never fail to try."
	// "It's okay to be loose."
	// "Do one thing every day that scares you."
	// "Practice make a perfection."
	// "Teamwork make a dreamwork."
	// "Believe you can and you're halfway there."
	// "Let your memory be your travel bag."
	// "To travel is to take ajourney into yourself."